[package]
name = "shsl-library"
version = "0.1.0"
authors = ["Delta-Psi <delta.psi00@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.4"
libc = "0.2.79"

[build-dependencies]
cbindgen = "0.15"

[lib]
crate-type = ["staticlib"]
